apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
    component: php
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
